### ISSUE TITLE
Convert database migrations to Flyway/Liquibase

### ISSUE THREAD

**Issue by cstroe** [mamutehq/mamute#4]
Currently Mamute keeps its database migrations in the following places:
* `src/main/resources/db_structure.sql` - this contains an initial database dump, before migrations were used.  This entire file has to be converted to Liquibase migrations.
* Java classes located at `src/main/migrations/org/mamute/migration/all` - Each one of these migrations needs to be converted to a Liquibase changeset.

We should migrate these to Flyway or Liquibase.

**Comment by cstroe** [comment]
Liquibase Docs: http://www.liquibase.org/documentation/existing_project.html

PROS to Liquibase:
* Can be DB independent
* Supports Rollback in Open Source version

CONS to Liquibase:
* More complicated, adds a layer of indirection between actual SQL that runs in the DB and migration files.

NEUTRAL to Liquibase:
* Has good documentation (but Flyway does too).

The most interesting one is that Liquibase migrations can be DB independent, which means that Mamute can automatically be used against databases other than MySQL, most notably Postgres.

Liquibase would also help if we want to use an in-memory DB at for DB tests, like HSQLDB which is one of the [supported databases](http://www.liquibase.org/databases.html).

**Comment by vicenthy** [comment]
i am having problems to access the site of liquibase because adobe flash required update in chrome browser, but i'm trying a initial config.

**Comment by icemagno** [comment]
Sorry my question but.... why not PostgreSQL ?

**Comment by cstroe** [comment]
Initial config for Liquibase is here: https://github.com/mamutehq/mamute/pull/6

I'd like to merge that first, before converting more of the migrations.

**Comment by cstroe** [comment]
Liquibase is managing migrations now, closing this.
